### ISSUE TITLE
Most of our games ended in timeout today

### ISSUE THREAD

**Issue by Zubry** [chausen/TigerZoneServer#5]
We're Team Q. If we run `grep TIMEOUT gamelogs/tournament-friday.txt` (which includes 2 challenges), we get the following

```
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 1 PLAYER TEAML FORFEITED: TIMEOUT
GAME 2 MOVE 2 PLAYER TEAML FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 1 PLAYER TEAMN FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMN FORFEITED: TIMEOUT
GAME 2 MOVE 1 PLAYER TEAMD FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMD FORFEITED: TIMEOUT
GAME 1 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 1 PLAYER TEAMH FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMH FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 1 PLAYER TEAMN FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMN FORFEITED: TIMEOUT
GAME 2 MOVE 1 PLAYER TEAMD FORFEITED: TIMEOUT
GAME 1 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 1 PLAYER TEAMH FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMH FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 2 MOVE 3 PLAYER TEAMQ FORFEITED: TIMEOUT
GAME 1 MOVE 2 PLAYER TEAMQ FORFEITED: TIMEOUT
```

So that's 19 * 2 * 2 76 games, 46 of which ended in timeout. 19 more never had a chance to timeout because the other team sent an illegal message on the first turn. We haven't recorded a response that takes longer than 750ms with a full board in our tests. We have a quick optimization to make that can get us down to about 300ms (which would prevent us from intelligently placing tigers), but I'd rather not do that until we know that the problem is on our end. [Here's](https://gist.github.com/Zubry/c6ed4fcac20191078cbea1e0d39f5a27) our full log if it helps.

**Comment by chausen** [comment]
We are using `setSoTimeout` for timeouts: 
https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#setSoTimeout(int)

Running tests on my home network (with a connection speed of about 60Mbps over WiFi) where I connect 24 clients to a server, I get the average network delay to be approximately 18245292 _ns_, or 18 _ms_. We have added a buffer to the timeout that more than accounts for this. In tests where I had clients purposely wait until 25 _ms_ before the timeout before sending their message, they didn't timeout. Finally, there are several other teams with sophisticated AIs and none of them have reported repeated timeouts. 

Given all of this, I'm not sure what else we can do. You have the ability to clone our repo and test against our server, so I would recommend doing whatever you have to to make sure your client doesn't timeout come Monday. Let us know if you find anything else. Thank you for commenting and good luck.

A different issue with timeouts that we have solved, but have not pushed to this public repo is discussed in issue https://github.com/chausen/TigerZoneServer/issues/7.
