### ISSUE TITLE
TIMEOUT causing future moves sent to be ILLEGAL MESSAGES even though they are formatted correctly

### ISSUE THREAD

**Issue by Martakia** [chausen/TigerZoneServer#7]
I believe I have finally deduced why all my messages are considered to be ILLEGAL MESSAGE RECEIVED after a TIMEOUT forfeit. We send the message for the move that takes longer than a second to calculate (which I believe I fixed) and then are told we forfeit due to a TIMEOUT. That forfeit is valid and deserved, but then each message we send afterward, even though it is formatted and correct, is considered an illegal message. I believe the server is parsing the message prior to the one that we send 

To be more clear with steps/workflow
1) TEAMR send move that takes more than 1 second
2) server tells us TEAMR time out
3) TEAMR responds to the make your move message the server sends for other games
4)Server detects that TEAMR sent a message, but parse and the previous message from TEAMR 
5)Server forfeits TEAMR for illegal move, even though we respond with a legal move for the message you sent us

I just don't know if this kind of thing is on the server or the client end. I would argue the server because we don't get the timeout message until we send the move that takes longer than a second we calculate (unless this is just by chance), so it is possible that the server needs to update the buffer reader with the new message when it comes in instead of being one message behind. The reason for the uncertainty is I think I know of a way to handle it on the client end, but It still requires the TIMEOUT forfeit message to trigger before my move ends up being sent. 

LOG INFO BELOW
[Tournament-server-Timeout-causing-illegal-messages-even-though-we-send-valid-messages.txt](https://github.com/chausen/TigerZoneServer/files/629906/Tournament-server-Timeout-causing-illegal-messages-even-though-we-send-valid-messages.txt)

Example of error from attached log file
12-02 13:30:53.598 | Recieving Response: MAKE YOUR MOVE IN GAME 2 WITHIN 1 SECOND: MOVE 6 PLACE JLJL-
2016-12-02 13:30:54.627 | SENDING: GAME 2 MOVE 6 PLACE JLJL- AT -2 0 270 NONE
2016-12-02 13:30:54.64 | Recieving Response: GAME 1 MOVE 6 PLAYER TEAMP PLACED JLJL- AT -1 -1 270 TIGER 2
2016-12-02 13:30:54.749 | Recieving Response: GAME 2 MOVE 6 PLAYER TEAMR FORFEITED: TIMEOUT
2016-12-02 13:30:54.819 | Recieving Response: MAKE YOUR MOVE IN GAME 1 WITHIN 1 SECOND: MOVE 7 PLACE LLLL-
2016-12-02 13:30:56.182 | SENDING: GAME 1 MOVE 7 PLACE LLLL- AT -1 -2 180 NONE
2016-12-02 13:30:56.266 | Recieving Response: GAME 1 MOVE 7 PLAYER TEAMR FORFEITED: ILLEGAL MESSAGE RECEIVED 
2016-12-02 13:30:56.372 | Recieving Response: GAME 1 OVER PLAYER TEAMR FORFEITED PLAYER TEAMP WIN
2016-12-02 13:30:56.445 | Recieving Response: GAME 2 OVER PLAYER TEAMP WIN PLAYER TEAMR FORFEITED
=====later in log=====
2-02 13:30:56.87 | Recieving Response: MATCH BEGINS IN 10 SECONDS
2016-12-02 13:31:04.654 | Recieving Response: MAKE YOUR MOVE IN GAME 1 WITHIN 1 SECOND: MOVE 1 PLACE TJJT-
2016-12-02 13:31:04.686 | SENDING: GAME 1 MOVE 1 PLACE TJJT- AT -1 0 0 TIGER 1
2016-12-02 13:31:04.687 | Recieving Response: GAME 1 MOVE 1 PLAYER TEAMR FORFEITED: ILLEGAL MESSAGE RECEIVED

**Comment by Martakia** [comment]
To add, this occurred during the tournament on Friday.

**Comment by chausen** [comment]
> I believe the server is parsing the message prior to the one that we send

> To be more clear with steps/workflow
> 
> TEAMR send move that takes more than 1 second
> server tells us TEAMR time out
> TEAMR responds to the make your move message the server sends for other games
> 4)Server detects that TEAMR sent a message, but parse and the previous message from TEAMR
> 5)Server forfeits TEAMR for illegal move, even though we respond with a legal move for the message you sent us

This is correct. It is the server's responsibility to handle this situation. This issue has been resolved and tested in our private repo (which we will be using for the tournament on Monday). If you're interested, look at `Match.java` and then `playerMatch()`. You'll see that the logic was in place, but had not been tested and was not setting the boolean that `Connection` uses to throw away the garbage on a read following a timeout. We cannot push the fix to this repo until after the _Extend & Evaluate_ assignment is over, but we will push it here after Wednesday.
