### ISSUE TITLE
NullPointerException on Invalid Meeple Placement

### ISSUE THREAD

**Issue by crepeau** [chausen/TigerZoneServer#8]
Team E. 

I think I have come across an issue in your code that can cause the server to crash when an invalid meeple placement occurs. Whenever I would send a meeple placement into zone 5 for the tile TTTT- (invalid, I know, but that was on our end), it would crash your server. 

Here are your server's logs: 
TEAMB HAS ENTERED THE TIGERZONE!
TEAMB joined
TEAME HAS ENTERED THE TIGERZONE!
TEAME joined
These are the tournament players TEAMB
These are the tournament players TEAME
BEGIN ROUND 1 OF 1
BEGIN ROUND 1 OF 1
YOUR OPPONENT IS PLAYER TEAME
STARTING TILE IS TLTJ- AT 0 0 0
Number of active threads from the given thread: 2
THE REMAINING 76 TILES ARE [ TLLT- TTTT- LJLJ- JJJJX TJTJ- TJTJ- TJTJ- LLJJ- TLTT- JJJJX TJTT- JLTTB JLLJ- TLTTP TLJTP LJJJ- LLJJ- TJJT- JLLJ- TJJT- TLJT- LJJJ- LLLL- TLLL- LJJJ- TJJT- TJTJ- TJJT- LJTJ- JLTTB JLJL- JJTJX TLLT- TJTT- JJTJX TJJT- LJJJ- JLLL- JJJJ- TJTJ- TLTJD TLLLC LLJJ- TLTTP LJTJD JLJL- JLTT- JLJL- LJJJ- TLTJ- TLLTB TLJTP TJJT- LLJJ- JLLL- LJTJD TJTT- TJJT- LJLJ- TLLTB LLJJ- LJLJ- TJTJ- TJTJ- TJJT- JJJJX TLTJ- TLLT- JLLL- TJJT- TLLLC TJTT- JLLL- TLTJD JJJJX TJTJ- ]
MATCH BEGINS IN 10 SECONDS
YOUR OPPONENT IS PLAYER TEAMB
STARTING TILE IS TLTJ- AT 0 0 0
THE REMAINING 76 TILES ARE [ TLLT- TTTT- LJLJ- JJJJX TJTJ- TJTJ- TJTJ- LLJJ- TLTT- JJJJX TJTT- JLTTB JLLJ- TLTTP TLJTP LJJJ- LLJJ- TJJT- JLLJ- TJJT- TLJT- LJJJ- LLLL- TLLL- LJJJ- TJJT- TJTJ- TJJT- LJTJ- JLTTB JLJL- JJTJX TLLT- TJTT- JJTJX TJJT- LJJJ- JLLL- JJJJ- TJTJ- TLTJD TLLLC LLJJ- TLTTP LJTJD JLJL- JLTT- JLJL- LJJJ- TLTJ- TLLTB TLJTP TJJT- LLJJ- JLLL- LJTJD TJTT- TJJT- LJLJ- TLLTB LLJJ- LJLJ- TJTJ- TJTJ- TJJT- JJJJX TLTJ- TLLT- JLLL- TJJT- TLLLC TJTT- JLLL- TLTJD JJJJX TJTJ- ]
MATCH BEGINS IN 10 SECONDS
Exception in thread "Thread-3" java.lang.NullPointerException
__        at com.tigerzone.fall2016.area.AreaManager.addTile(AreaManager.java:124)__
        at com.tigerzone.fall2016.gamesystem.GameSystem.receiveTurn(GameSystem.java:117)
        at com.tigerzone.fall2016.ports.IOPort.receiveTurnPlace(IOPort.java:165)
        at com.tigerzone.fall2016.ports.IOPort.receiveTurn(IOPort.java:110)
        at com.tigerzone.fall2016server.tournament.Game.receiveTurn(Game.java:60)
        at com.tigerzone.fall2016server.tournament.Match.playMatch(Match.java:146)
        at com.tigerzone.fall2016server.tournament.Match.run(Match.java:49)

Here is the log for the client that caused the server to crash: 

Server (TEAMB): THIS IS SPARTA!
Client: JOIN TIGERZONE
Server (TEAMB): HELLO!
Client: I AM TEAMB IAMB
Server (TEAMB): WELCOME TEAMB PLEASE WAIT FOR THE NEXT CHALLENGE
Server (TEAMB): NEW CHALLENGE 1 YOU WILL PLAY 1 MATCH
Server (TEAMB): BEGIN ROUND 1 OF 1
Server (TEAMB): YOUR OPPONENT IS PLAYER TEAME
Server (TEAMB): STARTING TILE IS TLTJ- AT 0 0 0
Server (TEAMB): THE REMAINING 76 TILES ARE [ TLLT- TTTT- LJLJ- JJJJX TJTJ- TJTJ- TJTJ- LLJJ- TLTT- JJJJX TJTT- JLTTB JLLJ- TLTTP TLJTP LJJJ- LLJJ- TJJT- JLLJ- TJJT- TLJT- LJJJ- LLLL- TLLL- LJJJ- TJJT- TJTJ- TJJT- LJTJ- JLTTB JLJL- JJTJX TLLT- TJTT- JJTJX TJJT- LJJJ- JLLL- JJJJ- TJTJ- TLTJD TLLLC LLJJ- TLTTP LJTJD JLJL- JLTT- JLJL- LJJJ- TLTJ- TLLTB TLJTP TJJT- LLJJ- JLLL- LJTJD TJTT- TJJT- LJLJ- TLLTB LLJJ- LJLJ- TJTJ- TJTJ- TJJT- JJJJX TLTJ- TLLT- JLLL- TJJT- TLLLC TJTT- JLLL- TLTJD JJJJX TJTJ- ]
Server (TEAMB): MATCH BEGINS IN 10 SECONDS
Server (TEAMB): MAKE YOUR MOVE IN GAME 1 WITHIN 1 SECOND: MOVE 1 PLACE TLLT-
Client: GAME 1 MOVE 1 PLACE TLLT- AT 0 1 90 TIGER 4
Server (TEAMB): GAME 1 MOVE 1 PLAYER TEAMB PLACED TLLT- AT 0 1 90 TIGER 4
Server (TEAMB): GAME 2 MOVE 1 PLAYER TEAME PLACED TLLT- AT 0 -1 0 TIGER 2
Server (TEAMB): MAKE YOUR MOVE IN GAME 2 WITHIN 1 SECOND: MOVE 2 PLACE TTTT-
__Client: GAME 2 MOVE 2 PLACE TTTT- AT -1 -1 270 TIGER 5__
Server (TEAMB): GAME 1 MOVE 2 PLAYER TEAME PLACED TTTT- AT -1 1 0 TIGER 2

It is kind of hard to replicate unless you explicitly place there from a client, but let me know if I'm wrong.

**Comment by matthewddiaz** [comment]
Hey Team E, Thanks for posting I'll take a look at it. We can't make modifications to this repository because of the on going assignment; but we are making changes in another repository. I'll let you know if we haven't already fixed that issue.

**Comment by matthewddiaz** [comment]
Hey Team E Forgot to comment back, but we fixed the issue before Monday's lecture (12/5/16). Thank you for notifying us.
-Team A
